# Generated by Django 5.0.4 on 2024-05-04 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Poll", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
